on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Inicia containers
        run: docker-compose up -d

      - name: Executa todos os testes dentro do container de teste
        run: docker-compose run --rm test-front

      - name: Para os containers
        run: docker-compose down
