on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v2

        - name: Instala o node com a versão
          uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: Instala o Angular CLI
          run: npm install -g @angular/cli

        - name: Instala as dependências
          run: npm install

        - name: Executa o lint para verificar se existem erros
          run: ng lint ./front
  tests:
      runs-on: ubuntu-latest
      steps:
          - name: Verifica o repositório do Git
            uses: actions/checkout@v2

          - name: Inicia containers
            run: docker-compose up -d

          - name: Instala o Angular CLI
            run: npm install -g @angular/cli

          - name: Instala as dependências
            run: npm install

          - name: Executa todos os testes
            run: npm run test

          - name: Para os containers
            run: docker-compose down