on: [push]

jobs:
  tests:
      runs-on: ubuntu-latest
      steps:
          - name: Verifica o repositório do Git
            uses: actions/checkout@v2

          - name: Inicia containers
            run: docker-compose up -d

          - name: Instala as dependências
            run: npm install

          - name: Executa todos os testes
            run: npm test

          - name: Para os containers
            run: docker-compose down