on: [push]

jobs:
  tests-front:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Inicia containers
        run: docker-compose up -d

      - name: Executa todos os testes dentro do container
        run: docker-compose exec -T app npm test

      - name: Para os containers
        run: docker-compose down
